version : "3.8"
services:
  db-timezone:
    restart: always
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: demo-timezone
      MYSQL_USER: demo
      MYSQL_PASSWORD: timezone
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./db-timezone:/var/lib/mysql
    ports:
      - "3306:3306"